### ISSUE TITLE
Fatal Error for Android 9 (Pie)

### ISSUE THREAD

**Issue by kerbooo** [hansemannn/titanium-firebase-analytics#36]
Hello I am getting below error. Module is working on emulator but not working on devices like Xiaomi MIA2

```
02-14 17:32:05.534 10443 10443 E AndroidRuntime: FATAL EXCEPTION: main
02-14 17:32:05.534 10443 10443 E AndroidRuntime: Process: com.sizebiz.just.live.basketball, PID: 10443
02-14 17:32:05.534 10443 10443 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN8titanium11KrollModule16getProxyTemplateEN2v85LocalINS1_7ContextEEE" referenced by "/data/app/com.sizebiz.just.live.basketball-brYMUgffwqCoZUL5AJLYhA==/lib/arm64/libfirebase.analytics.so"...
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1669)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:139)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:113)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:207)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:113)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:135)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at com.sizebiz.just.live.basketball.JustLiveBasketballApplication.onCreate(JustLiveBasketballApplication.java:159)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5885)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:200)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1651)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6692)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-14 17:32:05.534 10443 10443 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
My appc ti info as below

```
Operating System
  Name                        = Mac OS X
  Version                     = 10.12.6
  Architecture                = 64bit
  # CPUs                      = 2
  Memory                      = 8.0GB

Node.js
  Node.js Version             = 11.8.0
  npm Version                 = 6.5.0

Titanium CLI
  CLI Version                 = 5.1.1
  node-appc Version           = 0.2.44

Titanium SDKs
  7.5.1.v20190124152315
    Version                   = 7.5.1
    Install Location          = /Users/kerberos/Library/Application Support/Titanium/mobilesdk/osx/7.5.1.v20190124152315
    Platforms                 = iphone, android
    git Hash                  = 93a7e89867
    git Timestamp             = 1/24/2019 23:29
    node-appc Version         = 0.2.47
  7.5.0.GA
    Version                   = 7.5.0
    Install Location          = /Users/kerberos/Library/Application Support/Titanium/mobilesdk/osx/7.5.0.GA
    Platforms                 = iphone, android
    git Hash                  = 2e5a7423d0
    git Timestamp             = 11/15/2018 21:52
    node-appc Version         = 0.2.47
  7.4.2.GA
    Version                   = 7.4.2
    Install Location          = /Users/kerberos/Library/Application Support/Titanium/mobilesdk/osx/7.4.2.GA
    Platforms                 = iphone, android
    git Hash                  = 13aff1d7b4
    git Timestamp             = 11/19/2018 17:54
    node-appc Version         = 0.2.45
 
Mac OS X
  Command Line Tools          = installed

Intel® Hardware Accelerated Execution Manager (HAXM)
  Not installed

Java Development Kit
  Version                     = 1.8.0_131
  Java Home                   = /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home

Genymotion
  Path                        = not found
  Genymotion Executable       = not found
  Genymotion Player           = not found
  Home                        = not found

VirtualBox
  Executable                  = not found
  Version                     = unknown

Android SDK
  Android Executable          = not found
  ADB Executable              = /Users/kerberos/Library/android-sdk-macosx/platform-tools/adb
  SDK Path                    = /Users/kerberos/Library/android-sdk-macosx

Android NDK
  NDK Path                    = not found
  NDK Version                 = not found

Android Platforms
  1) android-10
    Name                      = Android 2.3.3 **Not supported by Titanium SDK 7.5.1.v20190124152315**
    API Level                 = 10
    Revision                  = null
    Skins                     = HVGA, QVGA, WQVGA400, WQVGA432, WVGA800, WVGA854
    ABIs                      = armeabi-v7a, x86
    Path                      = /Users/kerberos/Library/android-sdk-macosx/platforms/android-10
  2) android-16
    Name                      = Android 4.1.2 **Not supported by Titanium SDK 7.5.1.v20190124152315**
    API Level                 = 16
    Revision                  = 1
    Skins                     = HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800, WVGA854, WXGA720, WXGA800, WXGA800-7in
    ABIs                      = 
    Path                      = /Users/kerberos/Library/android-sdk-macosx/platforms/android-16
  3) android-23
    Name                      = Android 6.0
    API Level                 = 23
    Revision                  = 3
    Skins                     = HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800, WVGA854, WXGA720, WXGA800, WXGA800-7in
    ABIs                      = 
    Path                      = /Users/kerberos/Library/android-sdk-macosx/platforms/android-23
  4) android-26
    Name                      = Android 8.0.0
    API Level                 = 26
    Revision                  = 1
    Skins                     = HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800, WVGA854, WXGA720, WXGA800, WXGA800-7in
    ABIs                      = 
    Path                      = /Users/kerberos/Library/android-sdk-macosx/platforms/android-26
  5) android-27
    Name                      = Android 8.1.0
    API Level                 = 27
    Revision                  = 1
    Skins                     = HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800, WVGA854, WXGA720, WXGA800, WXGA800-7in
    ABIs                      = 
    Path                      = /Users/kerberos/Library/android-sdk-macosx/platforms/android-27
  6) android-28
    Name                      = Android 9
    API Level                 = 28
    Revision                  = 1
    Skins                     = HVGA, QVGA, WQVGA400, WQVGA432, WSVGA, WVGA800, WVGA854, WXGA720, WXGA800, WXGA800-7in
    ABIs                      = x86
    Path                      = /Users/kerberos/Library/android-sdk-macosx/platforms/android-28

Android Add-Ons
  None

Android Emulators
  None

Genymotion Emulators
  None

Connected Android Devices
  None

Xcode
  9.2 (build 9C40b) - Xcode default
    Install Location          = /Applications/Xcode.app/Contents/Developer
    iOS SDKs                  = 11.2
    iOS Simulators            = 11.2
    Watch SDKs                = 4.2
    Watch Simulators          = 4.2
    Supported by TiSDK 7.5.1.v20190124152315 = yes
    EULA Accepted             = yes
    Teams                     = none
 
iOS Keychains
  login.keychain-db           = /Users/kerberos/Library/Keychains/login.keychain-db
  System.keychain             = /Library/Keychains/System.keychain

iOS Development Certificates
/Users/kerberos/Library/Keychains/login.keychain-db
  Mahmut Tiyek (8R5X3KDS3C)
    Not valid before          = 7/24/2018 1:31 AM
    Not valid after           = 7/24/2019 1:31 AM

iOS App Store Distribution Certificates
/Users/kerberos/Library/Keychains/login.keychain-db
  Mahmut Tiyek (8YDJT5V23L)
    Not valid before          = 7/24/2018 1:34 AM
    Not valid after           = 7/24/2019 1:34 AM

Apple WWDR Certificate
  Apple WWDR                  = installed

Development iOS Provisioning Profiles
  JLB Device Test
    UUID                      = dd61632b-405b-4ee4-a272-118a04f87c68
    App Prefix                = 8YDJT5V23L
    App Id                    = com.sizebiz.just.live.basketball
    Date Created              = 1/6/2019 3:49 AM
    Date Expired              = 1/6/2020 3:49 AM
    Managed                   = No
 
App Store Distribution iOS Provisioning Profiles
  JLB Distribution
    UUID                      = 860a7bc0-d50e-4898-99dd-b68ed984421f
    App Prefix                = 8YDJT5V23L
    App Id                    = com.sizebiz.just.live.basketball
    Date Created              = 7/24/2018 2:05 AM
    Date Expired              = 7/24/2019 1:34 AM
    Managed                   = No
 
Ad Hoc iOS Provisioning Profiles
  None

Enterprise Ad Hoc iOS Provisioning Profiles
  None

iOS Simulators
11.2
  iPad Air (ipad)
    UDID                      = 18A203AF-8A15-47E9-BBF8-49C055645D19
    Supports Watch Apps       = no
  iPad Air 2 (ipad)
    UDID                      = 7E251490-150D-44E1-A797-32A53DA43465
    Supports Watch Apps       = no
  iPad (5th generation) (ipad)
    UDID                      = 064DEEA8-AFF7-4C2E-92A6-54AFAADD1FC9
    Supports Watch Apps       = no
  iPad Pro (9.7-inch) (ipad)
    UDID                      = 8AC72C60-6D7D-4442-8CF2-8AFB486E72B9
    Supports Watch Apps       = no
  iPad Pro (12.9-inch) (ipad)
    UDID                      = 9856F80C-8CE1-4BAB-A85F-8B2F62377722
    Supports Watch Apps       = no
  iPad Pro (12.9-inch) (2nd generation) (ipad)
    UDID                      = BF03F2BA-9613-49CC-A138-7D05F4B8754A
    Supports Watch Apps       = no
  iPad Pro (10.5-inch) (ipad)
    UDID                      = A30B5957-5836-4033-9BF4-7A2DD75D7B75
    Supports Watch Apps       = no
  iPhone X (iphone)
    UDID                      = 4D0C74B6-7C2D-4F66-8FC3-BF8CB556F985
    Supports Watch Apps       = yes
  iPhone 8 (iphone)
    UDID                      = F60E2BEB-B408-479C-A489-8DD1D7CBCF73
    Supports Watch Apps       = yes
  iPhone 8 Plus (iphone)
    UDID                      = E3D7CF3A-2359-49D8-B4D1-D7E646254363
    Supports Watch Apps       = yes
  iPhone 5s (iphone)
    UDID                      = A0864645-3857-464F-A613-4165941CC8BA
    Supports Watch Apps       = yes
  iPhone 6 Plus (iphone)
    UDID                      = 761AB25C-CE1E-46EF-BD36-731D92D063A5
    Supports Watch Apps       = yes
  iPhone 6 (iphone)
    UDID                      = F919D335-6896-48D9-8275-D223A49519B8
    Supports Watch Apps       = yes
  iPhone 6s (iphone)
    UDID                      = A5E0E482-9DC0-4EF2-B825-E08F6635FE6E
    Supports Watch Apps       = yes
  iPhone 6s Plus (iphone)
    UDID                      = 3D1858E5-A7F0-4F39-A378-A1692B04E9B2
    Supports Watch Apps       = yes
  iPhone SE (iphone)
    UDID                      = 7DC7772F-6C51-4D40-871C-E4AE46881AB5
    Supports Watch Apps       = yes
  iPhone 7 (iphone)
    UDID                      = F676E144-AB5C-4B59-898D-EF61E648BAEA
    Supports Watch Apps       = yes
  iPhone 7 Plus (iphone)
    UDID                      = 17EE1937-C61D-42E0-818C-49E934F3BC4B
    Supports Watch Apps       = yes

WatchOS Simulators
4.2
  Apple Watch - 38mm (watch)
    UDID                      = 2F89A688-72D1-4219-A6AC-19DA6D5343EE
  Apple Watch - 42mm (watch)
    UDID                      = C2A27A27-2B8D-4EA2-AE76-CC1DB1834BBA
  Apple Watch Series 2 - 38mm (watch)
    UDID                      = CF951364-8B4C-4365-82A2-751B372031BE
  Apple Watch Series 2 - 42mm (watch)
    UDID                      = F9A877E1-0DAC-4AB9-A3EF-7897679919BE
  Apple Watch Series 3 - 38mm (watch)
    UDID                      = CDF6A36E-0048-418D-A600-178CF1E6C581
  Apple Watch Series 3 - 42mm (watch)
    UDID                      = 6EBCA80C-C0D6-475C-B1D4-FE05FA08B996

Connected iOS Devices
  None

Android Issues
  !  Unable to locate an Android NDK.
     Without the NDK, you will not be able to build native Android Titanium modules.
     If you have already downloaded and installed the Android NDK, you can tell Titanium where the
     Android NDK is located by running 'appc titanium config android.ndkPath /path/to/android-ndk',
     otherwise you can install it by running 'appc titanium setup android' or manually downloading
     from http://appcelerator.com/android-ndk.

  !  Android API Android 2.3.3 (android-10) is too old and is no longer supported by Titanium SDK
     7.5.1.
     The minimum supported Android API level by Titanium SDK 7.5.1 is API level 23.

  !  Android API Android 4.1.2 (android-16) is too old and is no longer supported by Titanium SDK
     7.5.1.
     The minimum supported Android API level by Titanium SDK 7.5.1 is API level 23.

iOS Issues
  !  Unable to find any valid iOS adhoc provisioning profiles.
     This will prevent you from packaging apps for adhoc distribution.
     You will need to log in to http://appcelerator.com/ios-dist-certs with your Apple Developer
     account, then create, download, and install a profile.
```

**Comment by kerbooo** [comment]
Hello everyone I need help so much about this issue. I have not solved since 1 month. I am getting same error when I use ti.ga module.

**Comment by hansemannn** [comment]
Please open a Appc-JIRA ticket for this as it is no module error but may be an issue in the V8 bridge.

**Comment by kerbooo** [comment]
https://jira.appcelerator.org/plugins/servlet/mobile#issue/AC-6133

**Comment by hansemannn** [comment]
Closing since this is rather an SDK ticket. See [TIMOB-26871](https://jira.appcelerator.org/browse/TIMOB-26871) for a solution - it seemed to be an outdated library.
